CREATE USER delibuser IDENTIFIED BY Delib2025;
GRANT CONNECT, RESOURCE TO delibuser;

CREATE TABLE delibuser.citoyens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(100),
    prenom VARCHAR2(100),
    date_naissance DATE,
    ville VARCHAR2(100)
);

CREATE TABLE delibuser.votes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_citoyen NUMBER,
    id_deliberation NUMBER,
    vote VARCHAR2(10),
    FOREIGN KEY (id_citoyen) REFERENCES delibuser.citoyens(id)
);
